### ISSUE TITLE
No tags

### ISSUE THREAD

**Issue by takluyver** [pygame/pygamefullmirror#1]
This mirror doesn't mirror the tags from hg, which are necessary for getting the Mac wheel builds back.

For [my mirror](https://github.com/takluyver/pygame), which currently builds the OSX wheels, I use the [hg-git](https://hg-git.github.io/) plugin. So my local hg repo has a repository path configured like this:

```
mygit = git+ssh://git@github.com:takluyver/pygame.git
```

And to update it, all I need to do is:

```
hg bookmark -r default master  # Mark hg's default branch as master for git
hg push mygit
```

This handles replicating tags. I'm happy to move that repo into this org if you give me the necessary access.

**Comment by takluyver** [comment]
I now have the access on GitHub to move my hg-git mirror into the pygame org. I intend to do so soon if there are no objections.

**Comment by illume** [comment]
Hi ya,

The tags were there... However, the branches don't automatically get imported when using hg-git. I noticed the branches are not on your repo either.

Github recommends this tool: https://github.com/frej/fast-export

I tried using that and it's much better - branches are there now. There's still a bunch of authors to map, and a couple of weirdly named branches which I think we don't need.

Please let me know if that's ok for you now?

cheers!

**Comment by takluyver** [comment]
Great, that works for me. When I get some time, I'll reconfigure the Travis releases thing to use this repo rather than my mirror.
